library(rgdal)
library(ggmap)
library(tidyverse)
library(plotly)
pv=readRDS("pv.rds")
vic=readRDS("vic.rds")
## object 'vic' is generated by the following code ---------
# aus=readOGR("poa_2011/POA_2011_AUST.shp")
# ausdf=fortify(aus,region="POA_CODE")
# 
# ## VIC data only
# vic=filter(ausdf,grepl("^3",ausdf$id))%>%
#   mutate(postcode=as.integer(id),
#          id=NULL)%>%
#   left_join(pv%>%distinct(postcode,cluster1,cluster2))

## two maps according to different clusters
c1=(vic%>%
  filter(!hole)%>%
  ggplot(aes(x=long,y=lat,group=group,fill=cluster1,text=postcode))+
  geom_polygon()+
  coord_fixed())%>%
  ggplotly()

c2=(vic%>%
      filter(!hole)%>%
      ggplot(aes(x=long,y=lat,group=group,fill=cluster2,text=postcode))+
      geom_polygon()+
      coord_fixed())%>%
  ggplotly()

print(c1)
print(c2)